apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-admin-plugin
    app.kubernetes.io/instance: gitops-admin-plugin
    app.openshift.io/runtime: nodejs
  name: gitops-admin-plugin
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitops-admin-plugin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gitops-admin-plugin
        app.kubernetes.io/instance: gitops-admin-plugin
        app.kubernetes.io/name: gitops-admin-plugin
        app.kubernetes.io/part-of: gitops-admin-plugin
    spec:
      containers:
      - image: quay.io/gnunn/gitops-admin-plugin:latest
        imagePullPolicy: Always
        name: gitops-admin-plugin
        ports:
        - containerPort: 9443
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/cert
          name: gitops-admin-plugin-cert
          readOnly: true
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          readOnly: true
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitops-admin-plugin-cert
        secret:
          defaultMode: 420
          secretName: gitops-admin-plugin-cert
      - configMap:
          defaultMode: 420
          name: gitops-admin-plugin
        name: nginx-conf
