apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-plugin-proxy
    app.kubernetes.io/instance: gitops-plugin-proxy
    app.openshift.io/runtime: go
  name: gitops-plugin-proxy
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: gitops-plugin-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gitops-plugin-proxy
    spec:
      containers:
      - image: quay.io/gnunn/gitops-plugin-proxy:4.16
        imagePullPolicy: Always
        name: gitops-plugin-proxy
        ports:
        - containerPort: 8443
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/certs
          name: gitops-plugin-proxy-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitops-plugin-proxy-certs
        secret:
          defaultMode: 420
          secretName: gitops-plugin-proxy-certs
