apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: gitops-admin-plugin
    app.kubernetes.io/instance: gitops-admin-plugin
    app.kubernetes.io/name: gitops-admin-plugin
    app.kubernetes.io/part-of: gitops-admin-plugin
  name: gitops-admin-plugin-patcher