apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ template "openshift-console-plugin.name" . }}
  labels:
    {{- include "openshift-console-plugin.labels" . | nindent 4 }}
spec:
  displayName: {{ default (printf "%s Plugin" (include "openshift-console-plugin.name" .)) .Values.plugin.description }}
  backend:
    service:
      basePath: {{ .Values.plugin.basePath }}
      name: {{ template "openshift-console-plugin.name" . }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.plugin.port }}
    type: Service
  proxy:
  - alias: token-exchange
    authorization: UserToken
    endpoint:
      type: Service
      service:
        name: plugin-token-exchange
        namespace: {{ .Release.Namespace }}
        port: 8443