apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-plugin-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitops-plugin-proxy
    app.kubernetes.io/name: gitops-plugin-proxy
    app.kubernetes.io/instance: gitops-plugin-proxy
    app.openshift.io/runtime: go
    app.kubernetes.io/part-of: gitops-admin-plugin
spec:
  selector:
    matchLabels:
      name: gitops-plugin-proxy
  replicas: 1
  template:
    metadata:
      labels:
        name: gitops-plugin-proxy
    spec:
      containers:
        - name: gitops-plugin-proxy
          image: quay.io/gnunn/gitops-plugin-proxy:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /mnt/certs
            name: gitops-plugin-proxy-certs
            readOnly: true
      volumes:
      - name: gitops-plugin-proxy-certs
        secret:
          defaultMode: 420
          secretName: gitops-plugin-proxy-certs